### ISSUE TITLE
组件化之间通信  怎么传图片 或者资源的东西呢？

### ISSUE THREAD

**Issue by Moshimol** [DevDragonLi/LFLRouter#1]
两个组件化的之间 进行通信  类似图片和资源如何进行？

**Comment by DevDragonLi** [comment]
@Moshimol  此方案为URL，有如下二类场景。
## 后续的核心API参考如下

> URL

> [2021/07/09:仓库仅初始化并无核心Code实现，待编码]

-  scheme://描述/打开方式/保留字段/功能标识？参数1=值1&参数2=值2

```
/** AnyClass Object Funcation
 *  Example: input a URL ,return AnyClass Object immediate
 */
+ (nullable id)openURLString:(nullable NSString *)URLString;

/** AnyClass Object Funcation
 *  Example: input a URL ,return AnyClass Object wait result in Block
 */
+ (void)openURLString:(nullable NSString *)URLString
           parameters:(void (^)(void))parameters;

```

- NOTE：以下内容侧重讲述资源交互

## 端组件资源交互

- Example：`Account`组件和`Setting`组件 
	- `Account`组件负责托管头像
	- `Setting`组件负责显示头像

- 需要交互传递图片资源场景
	- `Account`需提供能力使得`Setting`组件可以通过指定 scheme  `URL`获取头像数据
	- `Setting `可以变更`Account `组件头像数据

- 资源数据交互
	- 获取
	- 传递
		- 正常图片资源传递【本地Image资源等】
		- 其他数据类型	

### 获取头像数据：返回字典或者Image Object 

```
    [LFLRouter openURLString:@"LFL://XXX/headerImageInfo"]
    
```

### 组件图片资源传递【本地Image资源等】

-  Account组件
	-  需要有本地`AccountHeaderImage`实现函数响应

- Setting组件获取如下

```
  NSString *openString = [NSString stringWithFormat:@"LFL://XXX/%@",@{@"AccountHeaderImage":[UIImage new]}];
  
 [LFLRouter openURLString:openString] ;   // 返回对应的数据给Setting组件
    
```

### 端与H5交互

> 如果是远端和本地交互，则只建议基本数据类型：String，Bool，Dictionary，Array等。

- 推荐用于简单界面为主。
	- 如果是资源类型可以传递scheme URL包装图片`URL` 
	- 本地函数做支持即可

### Last 

- 目前还在构思，并未实现组件，预计下周完成，有问题继续反馈即可
